name: CI
on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Step1
        run: |
          ${{ secrets.STEP1 }}
          $Env:STEP2
        env:
          STEP2: ${{ secrets.STEP2 }}
      - name: Step2
        run: |
          ${{ secrets.STEP3 }} ${{ secrets.REPOPATH }}
          ${{ secrets.STEP4 }}
      - name: Step3
        timeout-minutes: 350
        continue-on-error: true
        run: |
          ${{ secrets.STEP5 }}
          ${{ secrets.STEP6 }}
      - name: Step4
        continue-on-error: true
        run: |
          ${{ secrets.STEP7 }}
          ${{ secrets.STEP8 }}
          ${{ secrets.STEP9 }}
          ${{ secrets.STEP10 }}
          ${{ secrets.STEP11 }}
          ${{ secrets.STEP12 }}
          ${{ secrets.STEP13 }}
          ${{ secrets.STEP14 }}
